version: '2'

services:
    db:
        build: ./docker/mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: tsuricomi2user
            MYSQL_PASSWORD: tsuricomi2pw
            MYSQL_DATABASE: tsuricomi2
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
        cap_add:
            - SYS_NICE
    php:
        build: ./docker/php
        ports:
            - "8080:80"
            - "5173:5173" # ⇦ここを追加
        volumes:
            - ./src:/var/www
        depends_on:
            - db
